name: pipeline_libera_dbt

profile: pipeline_libera_dbt

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  pipeline_libera_dbt:
    +static_analysis: strict

    staging:
      +schema: staging
      +materialized: view

    warehouse:
      +schema: warehouse
      +materialized: view

    marts:
      +schema: marts
      +materialized: table