SELECT
    id_venta,
    TRIM(UPPER(DESARROLLO_LARGO)) AS desarrollo_largo,
    TRIM(UPPER(DESARROLLO_CORTO)) AS desarrollo_corto,
    UNIDAD AS unidad,
    TRIM(ETAPA) AS etapa,
    TRIM(UPPER(ASESOR)) AS asesor,
    TRIM(STATUSVENTA) AS status_venta,
    FECHACONTRATO AS fecha_contrato,
    FECHAFIRMACONTRATO AS fecha_firma_contrato,
    PLAN AS plan,
    NOMENSUALIDADES AS num_mensualidades,
    PRECIOVENTA AS precio_venta,
    ENGANCHE AS enganche,
    FINANCIAMIENTO AS financiamiento,
    STATUSESCRITURA AS status_escritura,
    FECHAESCRITURA AS fecha_escritura,
    VALORESCRITURA AS valor_escritura,
    DIAPAGO AS dia_pago,
    TRIM(UPPER(NOMBRECLIENTE)) AS nombre_cliente,
    TRIM(UPPER(APELLIDOPATERNO)) AS apellido_paterno,
    TRIM(UPPER(APELLIDOMATERNO)) AS apellido_materno,
    TRIM(EDAD) AS edad,
    TRIM(LUGARNACIMIENTO) AS lugar_nacimiento,
    RFC AS rfc,
    CURP AS curp,
    CALLE AS calle,
    TRIM(NOEXTERIOR) AS no_exterior,
    TRIM(NOINTERIOR) AS no_interior,
    TRIM(UPPER(COLONIA)) AS colonia,
    CAST(CODIGOPOSTAL AS INT) AS codigo_postal,
    TRIM(UPPER(LOCALIDAD)) AS localidad,
    TRIM(UPPER(ESTADO)) AS estado,
    TRIM(UPPER(PAIS)) AS pais,
    TRIM(NACIONALIDAD) AS nacionalidad,
    TRIM(UPPER(OCUPACION)) AS ocupacion,
    EMAIL AS email,
    TELEFONOCELULAR AS telefono_celular,
    TELEFONOLOCAL AS telefono_local,
    TRIM(UPPER(IDENTIFICACION)) AS identificacion,
    TRIM(NOIDENTIFICACION) AS no_identificacion,
    CAST(FECHAPROSPECTACION AS DATE) AS fecha_prospectacion,
    CAST(FECHAREGISTROVENTA AS DATE) AS fecha_registro_venta, 
    TRY_CAST(NULLIF(TRIM(FECHAAPROBACIONJD), 'NULL') AS DATE) AS fecha_aprobacion_jd,
    TRY_CAST(NULLIF(TRIM(FECHAREGISTROCARGACONTRATO), 'NULL') AS DATE) AS fecha_registro_carga_contrato,
    ENTRODV AS entro_dv,
    TRIM(UPPER(SEXO)) AS sexo,
    TRIM(UPPER(ESTADOCIVIL)) AS estado_civil,
    TRIM(UPPER(REGIMEN)) AS regimen
FROM {{ source('raw', 'rp_copropiedades_canceladas') }}